name: Build and Push Mattermost Enterprise Edition

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  IMAGE_NAME: idevucs/mattermost-enterprise-edition
  # DOCKER_CONTEXT: server/build/docker

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive # important: enterprise code imports mattermost-server as a submodule

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_DEV_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DEV_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          provenance: false
          file: server/build/Dockerfile.buildenv
          push: true
          pull: true
          tags: ${{ env.IMAGE_NAME }}:latest
          build-args: |
            EDITION=enterprise

      - name: Image digest
        run: |
          echo "Image pushed: ${{ env.IMAGE_NAME }}:latest"
