name: Server CI Master
on:
  # push:
  #   branches:
  #     - master
  #     - release-*
  workflow_dispatch:

jobs:
  master-ci:
    uses: ./.github/workflows/server-ci-template.yml
    secrets: inherit
